language: node_js
node_js:
  - 'stable'
install:
  - yarn
before_script:
  - npx lerna run --scope @gql-gateway/graphql-user start &
  - npx lerna run --scope @gql-gateway/graphql-post start &
  - sleep 10
  - npx lerna run --scope @gql-gateway/graphql-gateway start &
  - sleep 10
script:
  - npx lerna run --scope @gql-gateway/app generate
  - npx lerna run --scope @gql-gateway/app tsc
  - npx apollo service:check
