language: node_js
node_js:
  - 'stable'
install:
  - yarn
before_script:
  - npx lerna run --scope @gql-gateway/pipelines graphql &
  - sleep 20
script:
  - npx lerna run --scope @gql-gateway/pipelines tsc
  - npx apollo service:check
