language: node_js
node_js:
  - 'stable'
install:
  - yarn
before_script:
  - nohup yarn --cwd packages/graphql-user start &
  - nohup yarn --cwd packages/graphql-post start &
  - sleep 10
  - nohup yarn --cwd packages/graphql-gateway start &
  - sleep 10
script:
  - yarn --cwd packages/app generate
  - yarn --cwd packages/app tsc
  - npx apollo service:check
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npx apollo service:push; fi
